import { WebhookError } from './error.js'

/**
 * Referral information attached to a message that originated from a
 * Click-to-WhatsApp ad or a Facebook/Instagram post.
 * Only present when the message was triggered by such an entry point.
 * Ref: https://developers.facebook.com/docs/whatsapp/cloud-api/guides/set-up-webhooks/
 */
export interface WebhookReferral {
  /**
   * URL of the ad or post that the user clicked
   */
  source_url: string

  /**
   * ID of the ad or post
   */
  source_id: string

  /**
   * Source type
   * - 'ad': Click-to-WhatsApp ad
   * - 'post': Facebook/Instagram post
   */
  source_type: 'ad' | 'post'

  /**
   * Body text of the ad or post
   */
  body?: string

  /**
   * Headline of the ad or post
   */
  headline?: string

  /**
   * Media type present in the ad or post
   */
  media_type?: 'image' | 'video'

  /**
   * URL of the image, present only for image ads
   */
  image_url?: string

  /**
   * URL of the video, present only for video ads
   */
  video_url?: string

  /**
   * URL of the video thumbnail, present only for video ads
   */
  thumbnail_url?: string

  /**
   * Click ID generated by Meta, used for ad attribution and reporting
   * Omitted for WhatsApp Status ad placements.
   */
  ctwa_clid?: string

  /**
   * Greeting/welcome message configured on the ad or post
   */
  welcome_message?: {
    text: string
  }
}

/**
 * Base interface for all WhatsApp webhook message types
 * Contains common fields shared across all message types
 */
export interface WebhookMessageBase {
  /**
   * Unique identifier for the message
   */
  id: string

  /**
   * Phone-number-based WhatsApp ID of the sender
   * May be omitted when the sender has adopted a WhatsApp username and the
   * business has had no recent phone-number interaction with them; use
   * `from_user_id` (the business-scoped user ID) in that case.
   */
  from?: string

  /**
   * Business-scoped user ID (BSUID) of the sender
   * Present in all messages webhooks regardless of username adoption.
   */
  from_user_id?: string

  /**
   * Parent business-scoped user ID of the sender
   * Only present for businesses enrolled in parent BSUIDs.
   */
  from_parent_user_id?: string

  /**
   * ID of the group the message was sent to
   * Only present for messages received in a WhatsApp group.
   */
  group_id?: string

  /**
   * Unix timestamp when WhatsApp server received the message
   */
  timestamp: string

  /**
   * Optional context information about the message
   * Reply/forward context do not co-occur; all sub-fields are optional.
   */
  context?: {
    /**
     * Indicates if the message was forwarded
     * Only included if forwarded 5 times or less.
     */
    forwarded?: boolean

    /**
     * Indicates if the message has been forwarded more than 5 times
     */
    frequently_forwarded?: boolean

    /**
     * WhatsApp ID of the sender of the message being replied to
     */
    from?: string

    /**
     * Message ID of the message being replied to
     */
    id?: string

    /**
     * Product the user is asking about
     * Present when the user messages the business about a specific catalog
     * product (product enquiry).
     */
    referred_product?: {
      /**
       * ID of the catalog the product belongs to
       */
      catalog_id: string

      /**
       * ID of the product in the catalog
       */
      product_retailer_id: string
    }
  }

  /**
   * Referral information when the message originated from a Click-to-WhatsApp
   * ad or a Facebook/Instagram post
   */
  referral?: WebhookReferral

  /**
   * Errors describing why a message could not be processed
   * Typically accompanies messages of type 'unknown' (e.g. unsupported
   * message types).
   */
  errors?: WebhookError[]

  /**
   * Type of message received
   */
  type:
    | 'text'
    | 'audio'
    | 'button'
    | 'contacts'
    | 'document'
    | 'image'
    | 'interactive'
    | 'location'
    | 'order'
    | 'reaction'
    | 'sticker'
    | 'system'
    | 'unknown'
    | 'video'
}

/**
 * Text message type received through webhook
 */
export interface WebhookTextMessage extends WebhookMessageBase {
  type: 'text'
  text: {
    /**
     * The actual text content of the message
     */
    body: string
  }
}

/**
 * Audio message type received through webhook
 */
export interface WebhookAudioMessage extends WebhookMessageBase {
  type: 'audio'
  audio: {
    /**
     * ID for the audio file
     */
    id: string
    /**
     * Mime type of the audio file
     */
    mime_type: string
  }
}

/**
 * Button message type received through webhook
 */
export interface WebhookButtonMessage extends WebhookMessageBase {
  type: 'button'
  button: {
    /**
     * The payload for a button clicked as part of an interactive message
     */
    payload: string
    /**
     * Button text
     */
    text: string
  }
}

/**
 * Document message type received through webhook
 */
export interface WebhookDocumentMessage extends WebhookMessageBase {
  type: 'document'
  document: {
    /**
     * ID for the document
     */
    id: string
    /**
     * Caption for the document, if provided
     */
    caption?: string
    /**
     * Name of the file
     */
    filename: string
    /**
     * Mime type of the document file
     */
    mime_type: string
  }
}

/**
 * Image message type received through webhook
 */
export interface WebhookImageMessage extends WebhookMessageBase {
  type: 'image'
  image: {
    /**
     * ID for the image
     */
    id: string
    /**
     * Caption for the image, if provided
     */
    caption?: string
    /**
     * Mime type of the image file
     */
    mime_type: string
    /**
     * SHA256 hash of the image
     */
    sha256: string
  }
}

/**
 * Interactive message type received through webhook
 */
export interface WebhookInteractiveMessage extends WebhookMessageBase {
  type: 'interactive'
  interactive: {
    /**
     * Type of interactive message
     */
    type: 'button_reply' | 'list_reply' | 'nfm_reply'
    /**
     * Button reply message payload
     */
    button_reply?: {
      /**
       * Unique ID for the button
       */
      id: string
      /**
       * Title of the button
       */
      title: string
    }
    /**
     * List reply message payload
     */
    list_reply?: {
      /**
       * Unique ID for the selected item
       */
      id: string
      /**
       * Title of the selected item
       */
      title: string
      /**
       * Description of the selected item
       */
      description: string
    }
    /**
     * NFM reply message payload
     */
    nfm_reply?: {
      /**
       * The name of the flow
       */
      name: string
      /**
       * The body/content of the flow
       */
      body: string
      /**
       * JSON response from the flow
       */
      response_json: string
    }
  }
}

/**
 * Order message type received through webhook
 */
export interface WebhookOrderMessage extends WebhookMessageBase {
  type: 'order'
  order: {
    /**
     * Catalog ID for the order
     */
    catalog_id: string
    /**
     * Product items in the order
     */
    product_items: {
      /**
       * Product ID
       */
      product_retailer_id: string
      /**
       * Quantity ordered
       */
      quantity: number
      /**
       * Item price
       */
      item_price: number
      /**
       * Currency code
       */
      currency: string
    }[]
  }
}

/**
 * Sticker message type received through webhook
 */
export interface WebhookStickerMessage extends WebhookMessageBase {
  type: 'sticker'
  sticker: {
    /**
     * ID for the sticker
     */
    id: string
    /**
     * Mime type of the sticker file
     */
    mime_type: string
    /**
     * SHA256 hash of the sticker
     */
    sha256: string
    /**
     * Whether the sticker is animated
     */
    animated: boolean
  }
}

/**
 * System message type received through webhook (e.g. a user changing their
 * phone number or business-scoped user ID)
 */
export interface WebhookSystemMessage extends WebhookMessageBase {
  type: 'system'
  system: {
    /**
     * Human-readable description of the system update
     * @example "User Sheena Nelson changed from 16505551234 to 12195555358"
     */
    body: string

    /**
     * Type of system update
     * - 'user_changed_number': the user changed their phone number
     * - 'user_changed_user_id': the user changed their phone number (the BSUID
     *   variant, which also carries the new `user_id`)
     */
    type?: 'user_changed_number' | 'user_changed_user_id'

    /**
     * The user's new phone-number-based WhatsApp ID
     * Omitted when the user has adopted a username and the phone number is
     * unavailable.
     */
    wa_id?: string

    /**
     * The user's new business-scoped user ID (BSUID)
     * Present for 'user_changed_user_id' system messages.
     */
    user_id?: string

    /**
     * The user's new parent BSUID
     * Only included if parent BSUIDs are enabled.
     */
    parent_user_id?: string

    /**
     * New WhatsApp ID if this was a customer number change message
     * @deprecated Legacy field from older API versions. Current (v25.0)
     * payloads carry the new ID in `wa_id` instead.
     */
    new_wa_id?: string
  }
}

/**
 * Video message type received through webhook
 */
export interface WebhookVideoMessage extends WebhookMessageBase {
  type: 'video'
  video: {
    /**
     * ID for the video
     */
    id: string
    /**
     * Caption for the video, if provided
     */
    caption?: string
    /**
     * Mime type of the video file
     */
    mime_type: string
    /**
     * SHA256 hash of the video
     */
    sha256: string
  }
}

/**
 * Reaction message type received through webhook
 * Sent when a user reacts to (or removes a reaction from) a message.
 */
export interface WebhookReactionMessage extends WebhookMessageBase {
  type: 'reaction'
  reaction: {
    /**
     * ID of the message the user reacted to
     */
    message_id: string

    /**
     * Emoji used for the reaction
     * Omitted entirely when the user removes their reaction (this is the
     * inbound convention; the send API uses an empty string to remove).
     */
    emoji?: string
  }
}

/**
 * Location message type received through webhook
 */
export interface WebhookLocationMessage extends WebhookMessageBase {
  type: 'location'
  location: {
    /**
     * Latitude of the shared location
     */
    latitude: number

    /**
     * Longitude of the shared location
     */
    longitude: number

    /**
     * Name of the location, if provided
     */
    name?: string

    /**
     * Address of the location, if provided
     */
    address?: string

    /**
     * URL for the location, usually only included for business locations
     */
    url?: string
  }
}

/**
 * A single contact within a contacts message received through webhook
 * Most properties may be omitted if the user chose not to share them; only
 * `name` (and within it, `formatted_name`) is reliably present.
 */
export interface WebhookMessageContact {
  /**
   * Contact name
   */
  name: {
    /**
     * Formatted full name (the only reliably present name field)
     */
    formatted_name: string
    first_name?: string
    last_name?: string
    middle_name?: string
    suffix?: string
    prefix?: string
  }

  /**
   * Contact phone numbers
   */
  phones?: {
    phone: string
    /**
     * WhatsApp ID for this phone number, if it belongs to a WhatsApp user
     */
    wa_id?: string
    type?: string
  }[]

  /**
   * Contact email addresses
   */
  emails?: {
    email: string
    type?: string
  }[]

  /**
   * Contact postal addresses
   */
  addresses?: {
    street?: string
    city?: string
    state?: string
    zip?: string
    country?: string
    country_code?: string
    type?: string
  }[]

  /**
   * Contact URLs
   */
  urls?: {
    url: string
    type?: string
  }[]

  /**
   * Contact organization information
   */
  org?: {
    company?: string
    department?: string
    title?: string
  }

  /**
   * Contact birthday in YYYY-MM-DD format
   */
  birthday?: string

  /**
   * Raw vCard for the shared contact
   * Present when the contact was shared via the share-contact flow with
   * origin 'other'.
   */
  vcard?: string

  /**
   * How the contact was shared
   * - 'contact_request': shared in response to a REQUEST_CONTACT_INFO prompt
   * - 'other': shared directly by the user
   */
  origin?: 'contact_request' | 'other'
}

/**
 * Contacts message type received through webhook
 */
export interface WebhookContactsMessage extends WebhookMessageBase {
  type: 'contacts'
  contacts: WebhookMessageContact[]
}

/**
 * Unknown message type received through webhook
 */
export interface WebhookUnknownMessage extends WebhookMessageBase {
  type: 'unknown'
}

/**
 * Union type of all possible webhook message types
 */
export type WebhookMessage =
  | WebhookTextMessage
  | WebhookAudioMessage
  | WebhookButtonMessage
  | WebhookContactsMessage
  | WebhookDocumentMessage
  | WebhookImageMessage
  | WebhookInteractiveMessage
  | WebhookLocationMessage
  | WebhookOrderMessage
  | WebhookReactionMessage
  | WebhookStickerMessage
  | WebhookSystemMessage
  | WebhookUnknownMessage
  | WebhookVideoMessage
