name: Dependabot auto-merge

on:
  pull_request:
    branches:
      - main

# Cancel if there is a build for the same branch running
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    if: github.actor == 'dependabot[bot]'

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Node version
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Run tests
        run: yarn test

      - name: Build
        run: yarn build

      # You can remove the next 2 steps to disable auto-merge.
      # These will fail if auto-merge is not enabled for the account repo.
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Enable auto-merge for Dependabot PRs
        if: startsWith(steps.metadata.outputs.update-type, 'version-update:semver')
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
